CREATE DATABASE	SQL_QLSV;
USE SQL_QLSV;
CREATE TABLE grade(
ID INT PRIMARY KEY NOT NULL,
MASV NVARCHAR(50),
TA FLOAT,
tin FLOAT,
GDTC FLOAT,
CONSTRAINT fk_st_gr FOREIGN KEY (MASV) REFERENCES student(MASV)
);
CREATE TABLE student(
MASV NVARCHAR(50) PRIMARY KEY NOT NULL,
hoten NVARCHAR(50),
email NVARCHAR(50),
SDT NVARCHAR(50),
Gioitinh BIT,
diachi NVARCHAR(50),
hinh NVARCHAR(50)
);
CREATE TABLE users(
username NVARCHAR(50),
password NVARCHAR(50),
role NVARCHAR(50)
);
DROP TABLE dbo.student
DROP TABLE dbo.grade
DROP TABLE dbo.users
SELECT TOP AS 