/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import ass.java3.Datavalidate;
import ass.java3.Message;
import ass.java3.StudentDAO;
import ass.java3.bangdiemDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import unit.Student;
import unit.bangdiem;

/**
 *
 * @author truon
 */
public class GPmanager extends javax.swing.JPanel {
    private Mainform parentForm;
    private DefaultTableModel tblmodel;
    /**
     * Creates new form GPmanager
     */
    public GPmanager() {
        initComponents();
        inittable();
        loadbangdiem();
    }
    private void inittable(){
        tblmodel = new DefaultTableModel();
        tblmodel.setColumnIdentifiers(new String[]{
            "MSSV","Tiếng Anh","Tin Học","GDTC","DTB"
        });
        tbGP.setModel(tblmodel);
    }
    private void loadbangdiem(){
        try {
            bangdiemDAO dao = new bangdiemDAO();
            List<bangdiem> list = dao.findtop(3);
            tblmodel.setRowCount(0);
            for(bangdiem bd :list){
                tblmodel.addRow(new Object[]{
                    bd.getMASV(),bd.getTA(),bd.getTin(),bd.getGDTC(),
                    (bd.getTA()+ bd.getTin()+ bd.getGDTC())/3
                });
            }
            tblmodel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            Message.showmessagedialog(parentForm,e.getMessage(),"lỗi");
        }
    }
    public void dodulieulencomponent(int row){
        if(row<0){
            return;
        }
        txtstudentID.setText(tbGP.getValueAt(row,0).toString());
        txtenglish.setText(tbGP.getValueAt(row,1).toString());
        txtit.setText(tbGP.getValueAt(row,2).toString());
        txtgdtc.setText(tbGP.getValueAt(row, 3).toString());
        lblGPA.setText(tbGP.getValueAt(row, 4).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGP = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        txtstudentIDsearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtstudentID = new javax.swing.JTextField();
        txtstudentname = new javax.swing.JTextField();
        txtenglish = new javax.swing.JTextField();
        txtit = new javax.swing.JTextField();
        txtgdtc = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblGPA = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();

        jButton6.setText("jButton6");

        tbGP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbGP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbGP);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("QUẢN LÝ ĐIỂM");

        jLabel2.setText("MÃ SINH VIÊN :");

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search.png"))); // NOI18N
        btnsearch.setText("tìm kiếm");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        txtstudentIDsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentIDsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtstudentIDsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnsearch)
                    .addComponent(txtstudentIDsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setText("MASV :");

        jLabel4.setText("HỌ TÊN :");

        jLabel5.setText("TIẾNG ANH :");

        jLabel6.setText("TIN HỌC :");

        jLabel7.setText("GDTC :");

        txtstudentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtstudentIDFocusLost(evt);
            }
        });

        txtenglish.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtenglishFocusLost(evt);
            }
        });

        txtit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtenglishFocusLost(evt);
            }
        });
        txtit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitActionPerformed(evt);
            }
        });

        txtgdtc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtenglishFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtstudentname, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(txtstudentID)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtenglish)
                            .addComponent(txtgdtc))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtstudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtstudentname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtenglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtgdtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ĐIỂM TRUNG BÌNH :");

        lblGPA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGPA.setText("0.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblGPA)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addComponent(lblGPA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add.png"))); // NOI18N
        btnnew.setText("NHẬP MỚI");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save.png"))); // NOI18N
        btnsave.setText("LƯU");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete.png"))); // NOI18N
        btndelete.setText("XÓA");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit.png"))); // NOI18N
        btnupdate.setText("CẬP NHẬT");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnew)
                    .addComponent(btnsave)
                    .addComponent(btndelete)
                    .addComponent(btnupdate))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbGPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGPMouseClicked
        int row=tbGP.getSelectedRow();
        dodulieulencomponent(row);
    }//GEN-LAST:event_tbGPMouseClicked

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        try {
            bangdiemDAO dao = new bangdiemDAO();
            bangdiem bd = dao.findbyID(txtstudentIDsearch.getText());
            if(bd != null){
                txtstudentID.setText(bd.getMASV());
                txtenglish.setText(String.format("%.2f",bd.getTA()));
                txtit.setText(String.format("%.2f",bd.getTin()));
                txtgdtc.setText(String.format("%.2f",bd.getGDTC()));
                
                txtstudentIDFocusLost(null);
                txtenglishFocusLost(null);
            }else{
                Message.showErrordialog(parentForm,"không tìm thấy sinh viên có mã theo yêu cầu","thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            Message.showErrordialog(parentForm, e.getMessage(), "lỗi");
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtstudentIDsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentIDsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentIDsearchActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        txtenglish.setText("");
        txtgdtc.setText("");
        txtstudentID.setText("");
        txtit.setText("");
        txtstudentname.setText("");
        
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        StringBuilder str = new StringBuilder();
        Datavalidate.validate(txtstudentID, str, "Hãy Nhập mã sinh viên");
        Datavalidate.validate(txtenglish, str, "Hãy Nhập Điểm TA");
        Datavalidate.validate(txtgdtc, str, "Hãy Nhập Điểm GDTC");
        Datavalidate.validate(txtit, str, "Hãy Nhập Điểm Tin");
        if(str.length()>0){
            Message.showErrordialog(parentForm, str.toString(), "Lỗi");
            return;
        }
        try {
            bangdiem bd = new bangdiem();
            bd.setMASV(txtstudentID.getText());
            bd.setTA(Float.parseFloat(txtenglish.getText()));
            bd.setTin(Float.parseFloat(txtit.getText()));
            bd.setGDTC(Float.parseFloat(txtgdtc.getText()));
            bangdiemDAO dao = new bangdiemDAO();
            if(dao.insert(bd)){
                Message.showmessagedialog(parentForm, "lưu thành công", "Thông báo");
                loadbangdiem();
            }else{
                Message.showmessagedialog(parentForm, "lưu thất bại", "Thông báo");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            Message.showErrordialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        StringBuilder str = new StringBuilder();
        Datavalidate.validate(txtstudentID, str, "Hãy Nhập mã sinh viên");
        if(str.length()>0){
            Message.showErrordialog(parentForm, str.toString(), "lỗi");
        }
        
        if(Message.showconfirmdialog(parentForm, "bạn có chắc muốn xóa sinh viên hay không ?", "Lưu ý") == JOptionPane.NO_OPTION){
            return;
        }
        try {
            bangdiemDAO dao = new bangdiemDAO();
            if(dao.delete(txtstudentID.getText())){
                Message.showmessagedialog(parentForm, "Sinh viên đã được xóa", "Thông báo");
                btnnewActionPerformed(evt);
                loadbangdiem();
            }else{
                Message.showconfirmdialog(parentForm, "Sinh viên không được xóa", "Lưu Ý");
            }
        } catch (Exception e) {
        e.printStackTrace();
            Message.showErrordialog(parentForm,e.getMessage(), "lỗi");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        StringBuilder str = new StringBuilder();
        Datavalidate.validate(txtstudentID, str, "Hãy Nhập mã sinh viên");
        Datavalidate.validate(txtenglish, str, "Hãy Nhập Điểm TA");
        Datavalidate.validate(txtgdtc, str, "Hãy Nhập Điểm GDTC");
        Datavalidate.validate(txtit, str, "Hãy Nhập Điểm Tin");
        if(str.length()>0){
            Message.showErrordialog(parentForm, str.toString(), "Lỗi");
            return;
        }
        try {
            bangdiem bd = new bangdiem();
            bd.setMASV(txtstudentID.getText());
            bd.setTA(Float.parseFloat(txtenglish.getText()));
            bd.setTin(Float.parseFloat(txtit.getText()));
            bd.setGDTC(Float.parseFloat(txtgdtc.getText()));
            bangdiemDAO dao = new bangdiemDAO();
            if(dao.update(bd)){
                Message.showmessagedialog(parentForm, "Cập nhật thành công", "Thông báo");
                loadbangdiem();
            }else{
                Message.showmessagedialog(parentForm, "Cập nhật thất bại", "Thông báo");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            Message.showErrordialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtstudentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstudentIDFocusLost
        try {
             StudentDAO dao = new StudentDAO();
            Student sv= dao.findbyID(txtstudentID.getText());
            if(sv != null){
                txtstudentname.setText(sv.getHoten());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtstudentIDFocusLost

    private void txtenglishFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtenglishFocusLost
        if(txtenglish.getText().equals("")||
                txtit.getText().equals("")||
                txtgdtc.getText().equals("")){
            return;
        }
        float ta = Float.parseFloat(txtenglish.getText());
        float it = Float.parseFloat(txtit.getText());
        float pt = Float.parseFloat(txtgdtc.getText());
        
        float avg = (ta + it + pt)/3;
        
        String st = String.format("%.2f", avg);
        lblGPA.setText(st);
    }//GEN-LAST:event_txtenglishFocusLost

    private void txtitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JTable tbGP;
    private javax.swing.JTextField txtenglish;
    private javax.swing.JTextField txtgdtc;
    private javax.swing.JTextField txtit;
    private javax.swing.JTextField txtstudentID;
    private javax.swing.JTextField txtstudentIDsearch;
    private javax.swing.JTextField txtstudentname;
    // End of variables declaration//GEN-END:variables
}
